# Generated by Django 4.2.2 on 2023-07-19 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент сервиса',
                'verbose_name_plural': 'Клиенты сервиса',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='Время рассылки')),
                ('frequency', models.CharField(choices=[(None, 'Не указано'), ('OPD', 'Раз в день'), ('OPW', 'Раз в неделю'), ('OPM', 'Раз в месяц')], default=None, max_length=3, verbose_name='Периодичность')),
                ('sending_status', models.CharField(choices=[(None, 'Не указано'), ('created', 'Создана'), ('active', 'Запущена'), ('closed', 'Завершена')], default=None, max_length=7, verbose_name='Статус отправки')),
                ('message_title', models.CharField(max_length=250, verbose_name='Тема письма')),
                ('message_content', models.TextField(verbose_name='Содержание')),
                ('customers', models.ManyToManyField(to='mailing_service.customers', verbose_name='Клиенты')),
            ],
            options={
                'verbose_name': 'Настройка рассылки',
                'verbose_name_plural': 'Настройки рассылок',
                'ordering': ('sending_status',),
            },
        ),
        migrations.CreateModel(
            name='MessagesLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='Время последней попытки')),
                ('attempt_status', models.CharField(choices=[(None, 'Не указано'), ('received', 'Получено'), ('failed', 'Провалено')], default=None, max_length=8, verbose_name='Статус попытки')),
                ('server_response', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответ сервера')),
                ('mailing_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_service.mailingsettings', verbose_name='Настройки рассылки')),
            ],
            options={
                'verbose_name': 'Логи рассылки',
                'verbose_name_plural': 'Логи рассылок',
                'ordering': ('attempt_status',),
            },
        ),
    ]
