# Generated by Django 4.2.2 on 2023-08-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageslogs',
            name='server_response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ сервера'),
        ),
    ]
