# Generated by Django 4.2.2 on 2023-08-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ('pk',), 'permissions': [('block_user', 'Block or unblock customer')], 'verbose_name': 'Клиент сервиса', 'verbose_name_plural': 'Клиенты сервиса'},
        ),
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'ordering': ('pk', 'sending_status'), 'permissions': [('stop_mailing', 'Stop or run mailing')], 'verbose_name': 'Настройка рассылки', 'verbose_name_plural': 'Настройки рассылок'},
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='sending_status',
            field=models.CharField(choices=[('created', 'Создана'), ('active', 'Запущена'), ('closed', 'Завершена')], default='created', max_length=7, verbose_name='Статус отправки'),
        ),
    ]
